language: ruby
cache: bundler
bundler_args: --without docs
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
addons:
   code_climate:
     repo_token: 77e63028c53dc5df71ce553c8d9a82538c55e0d18b8a94c0619dc89f957c6417 

